### ISSUE TITLE
Strange crash in glXGetProcAddressARB

### ISSUE THREAD

**Issue by mittorn** [OpenSWR/openswr#6]
```
#0  0x00000000002e4c06 in ?? ()
#1  0x00007ffff0ae2f96 in glXGetProcAddressARB (procName=0x7ffff78ab75e "glXChooseVisual") at /mnt/data/openswr/ogldriver/glx.cpp:579
#2  0x00007ffff7891046 in ?? () from /usr/lib64/libSDL2-2.0.so.0
#3  0x00007ffff788551f in ?? () from /usr/lib64/libSDL2-2.0.so.0
```
```
#0  0x00007ffff0ae2f96 in glXGetProcAddressARB (procName=0x7ffff78ab75e "glXChooseVisual") at /mnt/data/openswr/ogldriver/glx.cpp:579
579         static void *handle = dlopen("libGL.so.1", RTLD_LOCAL | RTLD_LAZY);
```
Disabling optimizations does not help, tested on 5.9 and 5.3 gcc versions.

**Comment by timrowley** [comment]
Are you using mesa-master or the code from this github repository?  While we still use the issue tracker here, development now happens in the mesa master repository.

What application were you running?

**Comment by mittorn** [comment]
I cannot use mesa repository becaause i cannot build llvm-3.6+ on my machine, for some reason it does not combile in 32-bit abi
